### ISSUE TITLE
アイコン変更

### ISSUE THREAD

**Issue by Andyyyy64** [Andyyyy64/Laboratory-Database#62]

**Comment by hibiki333155555** [comment]
![](file:///var/folders/wq/drpdghd906v3k864t_7dnrw00000gn/T/TemporaryItems/NSIRD_screencaptureui_gguuRg/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202024-08-21%202.09.53.png)
