### ISSUE TITLE
下のスライドバーをなくす

### ISSUE THREAD

**Issue by Andyyyy64** [Andyyyy64/Laboratory-Database#66]
俺だけ？
![image](https://github.com/user-attachments/assets/8316d36e-b2b9-4fac-95f0-4bf6eb4b61d7)

**Comment by hibiki333155555** [comment]
<img width="1420" alt="スクリーンショット 2024-08-21 15 23 30" src="https://github.com/user-attachments/assets/aeaf699a-bcbc-4e08-bbb9-d472ace99028">

ある

**Comment by Andyyyy64** [comment]
おけ。ty
